### ISSUE TITLE
Python3.12 compatibility will require lxml 5.0.0

### ISSUE THREAD

**Issue by APCBoston** [ADTRAN/netconf_client#29]
While working on #28, I learned that CPython3.12 cannot build lxml < 5.0.0.  See https://github.com/streamlink/streamlink/issues/5336

**Comment by JennToo** [comment]
Interesting, we can probably just widen this range on the next release: https://github.com/ADTRAN/netconf_client/blob/c35237a6d232dbb0c05642b8446693cbd065b8f2/pyproject.toml#L20
