### ISSUE TITLE
 Module 'ssl' has no attribute 'wrap_socket'

### ISSUE THREAD

**Issue by wallrite** [ADTRAN/netconf_client#43]
Hello,

I'm porting the code to python 3.12, and getting error with TLS connection [here](https://github.com/ADTRAN/netconf_client/blob/fdd42a7e942d6b38fe1c1806e4265e49213f86c3/netconf_client/connect.py#L123)

[Here are](https://docs.python.org/3.12/library/ssl.html#socket-creation) some examples from official docs.

My environment:
OS: Ubuntu 20.04
Python: 3.12.3
netconf_client: 3.1.0

**Comment by JennToo** [comment]
That should be a pretty easy fix. Though I don't have access to a TLS-enabled NETCONF server right now to verify a fix. If you have like a docker container I can test against, I could try to fix this.

Or a PR is also welcome too!

**Comment by JennToo** [comment]
Released in 3.1.1. Thanks for the PR! <3
